### ISSUE TITLE
Lua

### ISSUE THREAD

**Issue by nt153133** [razfriman/NewWorldLib#1]
Not an issue but I wanted to mention something I found. After using your code to extract the game files I saw all the compiled luac scripts in the lyshineui and scripts folders. If you remove the first 2 bytes of the files you can run them through unluac_2021_09_23.jar and they become perfectly clean lua source files. Also the dds images can be converted to png files with a c# project called DDSReader if you update it's nuget packages to the newest versions. Not sure if it'll help your use case but since your project was very helpful in mine I figured I'd pass along the info.

**Comment by razfriman** [comment]
Much appreciated thank you for the information!!
